[profile.default]
evm_version = "paris"
fs_permissions = [{access = "read", path = "./"}]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "out"
solc = "0.8.19"
src = "src"
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
bracket_spacing = true
line_length = 120
