[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"

remappings = ['forge-std/=lib/forge-std/src/', 'solmate/=lib/solmate/src/']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
